### PR TITLE
dev-duplicate

### PR DESCRIPTION
**Pull request by jbalis-usgs**
Patched the web data connector to allow for handling of multiple instances of the same parameter from the same site.

### CODE REVIEW

**Comment by ayan-usgs** [comment]
Code looks fine. However, I wanted to if any metadata is being provided to distinguish between time-series for the same parameter at a site? I didn't see anything to that effect.

**Comment by jbalis-usgs** [comment]
Currently,  I am disambiguating  the repeated parameters with a numeric postfix. It does appear to be the case that methodDescription is unique between repeated parameters at least in the case our our examples, but there is no other disambiguating metadata, and I am not certain that methodDescription is guaranteed to be unique in all cases.

**Comment by ayan-usgs** [comment]
> I am not certain that methodDescription is guaranteed to be unique in all cases

That's probably true since hydrotechs enter that information and it would very based on entry. It however does mean it could carry something interpretative value to a human. I'm cool with the using numeric values, but I think it's important that a meaning value for a human also be sent along. It can either be a column in the table, appended to the table name, or whatever.

**Comment by jbalis-usgs** [comment]
Sounds good; I will add a method description column.

**Comment by jbalis-usgs** [comment]
The system is now configured so the methodDescription column is included, and guaranteed disambiguation is performed through index number appended to the table name as before.

**Pull request merged**
